services:
  meme-generator:
    build:
      context: ./src/app
    read_only: true
    hostname: "meme-generator"
    container_name: "meme-generator"
    image: anssi/fcsc2025-web-meme-generator:latest
    ports:
      - "8000:80"
    restart: always
    cap_drop:
      - all
    tmpfs:
      - /var/run/apache2/

  meme-generator-bot:
    build:
      context: ./src/bot
    read_only: true
    hostname: "meme-generator-bot"
    container_name: "meme-generator-bot"
    image: anssi/fcsc2025-web-meme-generator-bot:latest
    depends_on:
      - meme-generator
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - CHALLENGE_HOST=http://meme-generator/
    ports:
      - "4000:4000"
    restart: always
    cap_drop:
      - all
    tmpfs:
      - /tmp
